[project]
name = "src"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "jupyterlab>=4.3.4",
    "kagglehub>=0.3.6",
    "matplotlib>=3.10.0",
    "pandas>=2.2.3",
]
